<a href="https://colab.research.google.com/github/Gabrolo00/Gabrolo00.github.io/blob/main/Sessione_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# intro python
import torch

x = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])

print(x)
print(x.shape)
print(x.dtype)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])
torch.float32


In [13]:
numeri = [3, 7, 2, 9, 4]
numeri2 = []

totale = 0

for n in numeri:
  totale += n

print(totale)


numeri2 = [n * 2 if n > 7 else n for n in numeri if n > 4]
print(numeri2)


25
[7, 18]


In [14]:
numeri = [3, 7, 2, 9, 4]

print(numeri * 2)

[3, 7, 2, 9, 4, 3, 7, 2, 9, 4]


In [32]:
##INTRODUZIONE A NUMPY

import numpy as np

a = np.array([3, 7, 2, 9, 4])

print(a.mean(), a.max(), a.min())
print(a ** 2)
print(a[a > a.mean()])

5.0 9 2
[ 9 49  4 81 16]
[7 9]


In [34]:
m = np.array([[1, 2, 3],
              [4, 5, 6]])          # shape (2, 3)

v = np.array([10, 20, 30])         # shape (3,)

print(m + v)



[[11 22 33]
 [14 25 36]]


In [2]:
##INTRODUZIONE PYTORCH e tensori

import torch

t = torch.tensor([3., 7., 2., 9., 4.])

print(t * 2)
print(t.mean())
print(t[t > 4])
print(t.shape)

tensor([ 6., 14.,  4., 18.,  8.])
tensor(5.)
tensor([7., 9.])
torch.Size([5])


In [36]:
x = torch.tensor(3.0, requires_grad=True)
y = x ** 2

y.backward()
print(x.grad)

x = torch.tensor(2.0, requires_grad=True)
w = torch.tensor(5.0, requires_grad=True)

y = w * x + 1

y.backward()
print(x.grad)
print(w.grad)

tensor(6.)
tensor(5.)
tensor(2.)


In [37]:
a = torch.tensor(3.0, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)
c = torch.tensor(7.0, requires_grad=True)

z = a * b ** 2 + c

z.backward()
print(a.grad)
print(b.grad)
print(c.grad)

tensor(1.)
tensor(6.)
tensor(1.)


In [40]:
x = torch.tensor([3., 7., 2., 9., 4.])
w = torch.tensor([5., 7., 2., 1., 6.], requires_grad=True)
b = torch.tensor(2.0, requires_grad=True)

y = (w * x).sum() + b

y.backward()

print(w.grad)
print(b.grad)


tensor([3., 7., 2., 9., 4.])
tensor(1.)


In [49]:
#NEURONE TRAINING con forward, loss, backward, update, zero_grad
import torch

# Dati: il neurone deve imparare che y = 3x
x = torch.tensor([1., 2., 3., 4., 5.])
y_target = torch.tensor([3., 6., 9., 12., 15.])

# Peso iniziale casuale e bias
w = torch.tensor(0.5, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

lr = 0.01  # learning rate

for epoch in range(1000):
    # 1. FORWARD: calcola la predizione
    y_pred = w * x + b  # riempi tu

    # 2. LOSS: calcola l'errore (usa il mean squared error)
    loss =  ((y_pred - y_target) ** 2).mean() # riempi tu

    # 3. BACKWARD: calcola i gradienti
    loss.backward()


    # 4. UPDATE: aggiorna w e b (senza tracciare i gradienti)
    with torch.no_grad():
        w -= lr * w.grad
        b -= lr * b.grad

    # 5. AZZERA i gradienti per il prossimo giro
    w.grad.zero_()
    b.grad.zero_()

    if epoch % 10 == 0:
        print(f"Epoch {epoch}: loss={loss.item():.4f}, w={w.item():.4f}, b={b.item():.4f}")

Epoch 0: loss=343.7500, w=3.2500, b=0.7500
Epoch 10: loss=0.2677, w=2.8523, b=0.5331
Epoch 20: loss=0.1903, w=2.8755, b=0.4496
Epoch 30: loss=0.1353, w=2.8950, b=0.3791
Epoch 40: loss=0.0962, w=2.9115, b=0.3197
Epoch 50: loss=0.0684, w=2.9253, b=0.2696
Epoch 60: loss=0.0487, w=2.9370, b=0.2273
Epoch 70: loss=0.0346, w=2.9469, b=0.1917
Epoch 80: loss=0.0246, w=2.9552, b=0.1616
Epoch 90: loss=0.0175, w=2.9622, b=0.1363
Epoch 100: loss=0.0124, w=2.9682, b=0.1149
Epoch 110: loss=0.0088, w=2.9732, b=0.0969
Epoch 120: loss=0.0063, w=2.9774, b=0.0817
Epoch 130: loss=0.0045, w=2.9809, b=0.0689
Epoch 140: loss=0.0032, w=2.9839, b=0.0581
Epoch 150: loss=0.0023, w=2.9864, b=0.0490
Epoch 160: loss=0.0016, w=2.9886, b=0.0413
Epoch 170: loss=0.0011, w=2.9903, b=0.0348
Epoch 180: loss=0.0008, w=2.9919, b=0.0294
Epoch 190: loss=0.0006, w=2.9931, b=0.0248
Epoch 200: loss=0.0004, w=2.9942, b=0.0209
Epoch 210: loss=0.0003, w=2.9951, b=0.0176
Epoch 220: loss=0.0002, w=2.9959, b=0.0149
Epoch 230: loss=0.00

In [51]:
#TRAINING CON OPTIMIZER

#NEURONE TRAINING con forward, loss, backward, update, zero_grad
import torch

# Dati: il neurone deve imparare che y = 3x
x = torch.tensor([1., 2., 3., 4., 5.])
y_target = torch.tensor([3., 6., 9., 12., 15.])

# Peso iniziale casuale e bias
w = torch.tensor(0.5, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

lr = 0.01  # learning rate

optimizer = torch.optim.SGD([w, b], lr=lr)

for epoch in range(100):
    # 1. FORWARD: calcola la predizione
    y_pred = w * x + b  # riempi tu

    # 2. LOSS: calcola l'errore (usa il mean squared error)
    loss =  ((y_pred - y_target) ** 2).mean() # riempi tu

    # 3. BACKWARD: calcola i gradienti
    loss.backward()


    optimizer.step()     # aggiorna i pesi
    optimizer.zero_grad() # azzera i gradienti

    if epoch % 10 == 0:
        print(f"Epoch {epoch}: loss={loss.item():.4f}, w={w.item():.4f}, b={b.item():.4f}")

Epoch 0: loss=68.7500, w=1.0500, b=0.1500
Epoch 10: loss=0.3805, w=2.7093, b=0.5866
Epoch 20: loss=0.0671, w=2.8261, b=0.5968
Epoch 30: loss=0.0614, w=2.8391, b=0.5789
Epoch 40: loss=0.0574, w=2.8449, b=0.5597
Epoch 50: loss=0.0537, w=2.8501, b=0.5411
Epoch 60: loss=0.0501, w=2.8551, b=0.5231
Epoch 70: loss=0.0469, w=2.8599, b=0.5057
Epoch 80: loss=0.0438, w=2.8646, b=0.4888
Epoch 90: loss=0.0409, w=2.8691, b=0.4725


In [3]:
#Rete single layer

import torch.nn as nn

class SingleNeuron(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(5,1)

  def forward(self, x):
    return self.linear(x)

x = torch.tensor([1., 2., 3., 4., 5.]).reshape(-1, 5)
y_target = torch.tensor([3., 6., 9., 12., 15.]).reshape(-1, 1)



model = SingleNeuron()
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

print(x.shape)
print(y_target.shape)

for epoch in range(100):
  y_pred = model(x)
  loss = criterion(y_pred, y_target)
  loss.backward()
  optimizer.step()
  optimizer.zero_grad()

  if epoch % 10 == 0:
      print(f"Epoch {epoch}: loss={loss.item():.4f}")

print(model.linear.weight)
print(model.linear.bias)


torch.Size([1, 5])
torch.Size([5, 1])
Epoch 0: loss=127.2479
Epoch 10: loss=18.0000
Epoch 20: loss=18.0000
Epoch 30: loss=18.0000
Epoch 40: loss=18.0000
Epoch 50: loss=18.0000
Epoch 60: loss=18.0000
Epoch 70: loss=18.0000
Epoch 80: loss=18.0000
Epoch 90: loss=18.0000
Parameter containing:
tensor([[ 0.0982, -0.0210,  0.6129,  0.6982,  0.9033]], requires_grad=True)
Parameter containing:
tensor([-0.2040], requires_grad=True)


/usr/local/lib/python3.12/dist-packages/torch/nn/modules/loss.py:626: UserWarning: Using a target size (torch.Size([5, 1])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [6]:
#MNIST | 3 layer + RELU + dropout + train + test

import torch
import torch.nn as nn
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

train_data = datasets.MNIST(root='./data', train=True, download=True,
                            transform=transforms.ToTensor())
test_data = datasets.MNIST(root='./data', train=False, download=True,
                           transform=transforms.ToTensor())

# Prendi una singola immagine e guardala
image, label = train_data[0]
print(image.shape)
print(label)

# Le immagini in PyTorch seguono il formato [C, H, W]: canali, altezza, larghezza.

# 1 canale → scala di grigi (come nel tuo caso, probabilmente MNIST)
# 3 canali → RGB (rosso, verde, blu)
# 4 canali → RGBA (RGB + trasparenza)


class MLP(nn.Module):
  def __init__(self):
    super().__init__()
    self.layer1 = nn.Linear(784,256)
    self.layer2 = nn.Linear(256,128)
    self.layer3 = nn.Linear(128,10)
    self.relu = nn.ReLU()
    self.Dropout = nn.Dropout(0.2)

  def forward(self,x):
    x = x.view(-1,784)
    x = self.relu(self.layer1(x))
    x = self.Dropout(x)
    x = self.relu(self.layer2(x))
    x = self.Dropout(x)
    x = self.layer3(x)
    return x


train_loader = DataLoader(train_data, batch_size=64, shuffle=True)
test_loader = DataLoader(test_data, batch_size=64, shuffle=False)

model = MLP()
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

for epoch in range(5):
    model.train()
    for images, labels in train_loader:
        # scrivi tu i 4 passi: forward, loss, backward, update+zero_grad
        y_pred = model(images)
        loss = criterion(y_pred, labels)
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()



    if epoch % 1 == 0:
        print(f"Epoch {epoch}: loss={loss.item():.4f}")




torch.Size([1, 28, 28])
5
Epoch 0: loss=1.2649
Epoch 1: loss=0.4215
Epoch 2: loss=0.7120
Epoch 3: loss=0.3348
Epoch 4: loss=0.2186


In [10]:
model.eval()
correct = 0
total = 0

with torch.no_grad():
  for images, labels in train_loader:
      outputs = model(images)
      predicted = torch.argmax(outputs, dim=1)
      total += labels.size(0)
      correct += (predicted == labels).sum().item()



print(f"Accuracy: {correct/total*100:.2f}%")

Accuracy: 91.53%
